<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE homepage [
<!ELEMENT root (worksheet,Row,Home)>
<!ELEMENT worksheet (#CDATA)>
<!ATTLIST worksheet name CDATA #FIXED "Sheet1">
<!ELEMENT Row (#CDATA)>
<!ATTLIST Row index CDATA #REQUIRED>
<!ELEMENT Home (#PCDATA)>
]

<root>
    <worksheet name="Sheet1">
        <Row index="1">
            <Home>Courses</Home>
        </Row>
        <Row index="2">
            <Home>Machine learning</Home>
        </Row>
        <Row index="3">
            <Home/>
        </Row>
        <Row index="4"/>
        <Row index="5">
        <Row index="6">
            <Home>Data Structures</Home>
        </Row>
        <Row index="7">
            <Home/>
        </Row>
        <Row index="8">
            <Home/>
        </Row>
        <Row index="9">
            <Home/>
        </Row>
        <Row index="10">
            <Home>Web Development</Home>

        </Row>
        <Row index="11">
            <Home/>
        </Row>
        <Row index="12">
            <Home/>
        </Row>
        <Row index="13">
            <Home/>
        </Row>
        <Row index="14">
            <Home>Cyber Security</Home>
        </Row>
    </worksheet>
</root>