<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE homepage [
<!ELEMENT root (worksheet,Row,DATASTRUCTURES)>
<!ELEMENT worksheet (#CDATA)>
<ATTLIST worksheet name CDATA #FIXED "Sheet1">
<!ELEMENT Row (#CDATA)>
<<ATTLIST Row index CDATA #REQUIRED>
<!ELEMENT DATASTRUCTURES (#CDATA)>
]

<root>
    <worksheet name="Sheet1">
        <Row index="4">
            <DATASTRUCTURES>Overview Curriculum Prerequisites Instructor </DATASTRUCTURES>
        </Row>
        <Row index="6">
            <DATASTRUCTURES>COURSE OVERVIEW</DATASTRUCTURES>
        </Row>
        <Row index="8"/>
        <Row index="9">
            <DATASTRUCTURES>CURRICULUM</DATASTRUCTURES>
        </Row>
        <Row index="11"/>
        <Row index="12">
            <DATASTRUCTURES>PREREQUISITES</DATASTRUCTURES>
        </Row>
        <Row index="19"/>
        <Row index="20">
            <DATASTRUCTURES>INSTRUCTOR</DATASTRUCTURES>
        </Row>
        <Row index="22">
            <DATASTRUCTURES>Abhishek Kumar</DATASTRUCTURES>
        </Row>
        <Row index="23">
            <DATASTRUCTURES>-4.5 INSTRUCTOR RATINGS -32308 REVIEWS -251605 STUDENTS -33 COURSES</DATASTRUCTURES>
        </Row>
        <Row index="24">
            <DATASTRUCTURES>I am working as Computer Scientist at Adobe. I have 7 years of extensive experience in Programming. I am a Machine Learning enthusiast and have 4+ years of experience in Machine Learning.I am very passionate about learning the latest developments in Computer Vision and Machine Learning and like sharing my knowledge with others. </DATASTRUCTURES>
        </Row>
    </worksheet>
</root>