<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE paymentsuccess [
    <!ELEMENT paymentsuccess (page, Row)>
    <!ELEMENT page (#PCDATA)>
    <!ELEMENT Row (#PCDATA)>
]>

<paymentsuccess>
    <page name="paymentsuccess">
    <Row  index="1"><✓>Payment Successful!!</✓></Row >
    <Row  index="3">
    <✓>Your course has been purchased.
    Happy Learning!</✓>
    </Row >
    <Row  index="4"><✓>Go back to the homepage.</✓></Row >
    </page>
</paymentsuccess>